ALTER TABLE document ADD COLUMN Contexte TEXT
ALTER TABLE document ADD COLUMN Problematique TEXT
ALTER TABLE document ADD COLUMN Objectif TEXT
ALTER TABLE document ADD COLUMN BienUneEtude TEXT
ALTER TABLE document ADD COLUMN Analyse TEXT
ALTER TABLE document ADD COLUMN MaitreOeuvre TEXT
ALTER TABLE document ADD COLUMN Logiciels TEXT
ALTER TABLE document ADD COLUMN Cnil TEXT

ALTER TABLE document ADD COLUMN Commercial VARCHAR(40);
ALTER TABLE document ADD COLUMN TypeClient VARCHAR(40);
ALTER TABLE document ADD COLUMN Contact VARCHAR(40);
ALTER TABLE document ADD COLUMN Signataire VARCHAR(40);
ALTER TABLE document ADD COLUMN Payeur VARCHAR(40);